version: '3'

services:

###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:10.4.27'
    container_name: db_test
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_ROOT_PASSWORD: ""
      MARIADB_DATABASE: "npp"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306'
    networks:
      - dev

networks:
  dev:
volumes:
  db-data: